# Generated by Django 2.1.5 on 2020-02-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WP', '0002_repair_parts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair_parts',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
