from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

app_name="WP"


urlpatterns = [

    path('admin/', admin.site.urls,name="admin"),
    path('',views.index,name="index"),
    path('login/',views.login,name="login"),
    path('logout/',views.logout_user,name="logout"),
    path('CreateWaterPlant/',views.CreateWaterPlant,name="CreateWaterPlant"),
    path('CreateWaterPlantLoc/',views.CreateWaterPlantLoc,name="CreateWaterPlantLoc"),
    path('WaterPlantLocDB/',views.WaterPlantLocDB,name="WaterPlantLocDB"),
    path('SetWarrentyDate/',views.SetWarrentyDate,name="SetWarrentyDate"),
    path('WaterPlantLocUpdate/<int:pk>/',views.WaterPlantLocUpdate,name="WaterPlantLocUpdate"),
    path('WaterPlantLocDelete/<int:pk>/',views.WaterPlantLocDelete,name="WaterPlantLocDelete"),
    path('CreateWaterPlantLocViaImport/',views.CreateWaterPlantLocViaImport,name="CreateWaterPlantLocViaImport"),
    path('ajax/load-mandal/',views.load_mandal,name='ajax_load_mandal'),
    path('ajax/load-gram_panchayat/',views.load_gram_panchayat,name='ajax_load_gram_panchayat'),
    path('ajax/load-village/',views.load_village,name='ajax_load_village'),
    path('ajax/load-constency/',views.load_constency,name='ajax_load_constency'),
    path('WaterPlantsDB/New/',views.view_new_water_plants,name='list-of-new-water-plants'),
    path('WaterPlantsDB/AMC/',views.view_amc_water_plants,name='list-of-amc-water-plants'),
    path('WaterPlantUpdate/<int:pk>/',views.WaterPlantUpdate,name="WaterPlantUpdate"),
    path('WaterPlantUpdateForm/<int:pk>/',views.UpdateWaterPlant_form,name="WaterPlantUpdate-form"),
    path('WaterPlantDelete/<int:pk>/',views.WaterPlantDelete,name="WaterPlantDelete"),
    path('ajax_new_filtertable/',views.ajax_filtertable_new,name='filter-ajax'),
    path('ajax_old_filtertable/',views.ajax_filtertable_old,name='filter-old-ajax'),
    path('AddConsumables/',views.AddConsumbles,name='AddConsumbles'),
    path('CostManagemnt/',views.cost_management,name="cost-management"),
    path('ajax_get_wp_name/',views.ajax_get_wp_name,name='ajax_get_wp_name'),
    path('ajax/load-mandal/wp',views.load_mandal_wp,name='ajax_load_mandal_wp'),
    path('ajax/load-gram_panchayat/wp',views.load_gram_panchayat_wp,name='ajax_load_gram_panchayat_wp'),
    path('ajax/load-village/wp',views.load_village_wp,name='ajax_load_village_wp'),
    path('ajax/load-constency/wp',views.load_constency_wp,name='ajax_load_constency_wp'),
    path('consumablesDB/',views.consumables_list,name="consumables_list"),
    path('table_consumable_list/',views.table_consumable_list,name="table_consumable_list"),
    path('consumables/delete/<int:pk>',views.ConsumablesDelete,name='ConsumablesDelete'),
    path('cost/delete/<int:pk>',views.deleteCost,name='CostDelete'),
    path('AddRepairParts/',views.AddRepairParts,name='AddRepairParts'),
    path('RepairPartsDB/',views.RepairPartsDB,name='RepairPartsDB'),
    path('AjaxRepairPartsBB/',views.table_repair_parts_data,name='table_repair_parts_data'),
    path('deleteRepairParts/<int:pk>',views.deleteRepairParts,name='deleteRepairParts'),
    path('consumable_track/',views.view_consumable_track,name='consumable_track'),
    path('ajax/get_years/',views.get_years,name='get_years'),
    path('ajax_view_consumable_track/',views.ajax_view_consumable_track,name='ajax_view_consumable_track'),
    path('ajax_view_consumable_track_yearly/',views.view_consumable_track_yearly,name='view_consumable_track_yearly'), 
    path('financial_track/',views.view_financial_track,name='financial_track'),
    path('ajax_view_financial_track/',views.ajax_view_financial_track,name='ajax_view_financial_track'),
    path('ajax_view_financial_track_yearly/',views.view_financial_track_yearly,name='view_financial_track_yearly'), 
    path('monthly_consumable_bar_gph/',views.monthly_consumable_bar_gph,name='monthly_consumable_bar_gph'),
    path('get_water_plants/',views.get_water_plants,name='get_water_plants'),
    path('monthly_bar_graph/',views.monthly_bar_graph,name='monthly_bar_graph'),
    path('monthly_financial_bar_gph/',views.monthly_financial_bar_gph,name='monthly_financial_bar_gph'),
    path('monthly_bar_graph_f/',views.monthly_bar_graph_f,name='monthly_bar_graph_f'),
    path('cost_management_graph/',views.cost_management_graph,name='cost_management_graph'),
    path('complete_water_plant_report/<int:pk>',views.complete_water_plant_report,name='complete_water_plant_report'),
    path('water_plant_import/',views.water_plant_import,name='water-plant-import'),
    path('sample_download/',views.sample_download,name='sample_download'),
    path('wpnew/export/',views.wpnew_export,name='wpnew-export'),
    path('wpamc/export/',views.wpamc_export,name='wpamc-export'),
    path('DetailFinancialReport/<int:pk>',views.detailed_FP,name='detailed_FP'),
    path('complete_financial_report/',views.complete_financial_report,name='complete_financial_report'),
    path('ReportGenerator/',views.ReportGenerator,name='ReportGenerator'),
    path('Notifications/',views.NotificationManager,name='notifications'),
    path('AddConsumables_withpk/<int:pk>',views.AddConsumables_withpk,name='AddConsumables_withpk'),
    path('AddConsumblesPK/<int:pk>',views.AddConsumblesPK,name='AddConsumblesPK'),
    path('ReportPage/',views.ReportPage,name='ReportPage'),
    path('SettingsPage/',views.SettingPage,name='SettingPage'),
    path('WaterPlantPage/',views.WPPage,name='WaterPlantPage'),
    path('Incharge/Add/',views.InchargeCreateView.as_view(),name='CreateIncharge'),
]
